### ISSUE TITLE
Not an issue, but a request :)

### ISSUE THREAD

**Issue by fregattenfahrer** [cpierquet/coloredbelts#1]
Hey Cedric,

just stumbled upon your nice package - works fine so far. Would it be possible to add some "in-between" belts with a centered colored stripe - would be nice for usage in martial arts curriculum definition for the (mostly) kids and tween grades, represented by like "white-yellow", "yellow-orange",  "orange-green", "green-blue", "blue-purple", "blue-brown", "pruple-brown" and last "brown-black" (where second color always represents the color of the stripe).

Greetings

**Comment by cpierquet** [comment]
Hi, colored belts come from svg converted to pdf, so (for the moment) monochrome, but I can look for modify (if it's easy) svg in order to obtain "in-between"...
Could you send a picture to show the render you want ?

**Comment by fregattenfahrer** [comment]
Hey Cedric,

I altered the SVG and created PDFs from them - if colors need to be other values, I may correct them :). Was quickly done with Inkscape. I also attached the altered SVG file. Hope, this helps.
![Judo_yellow_white_belt](https://github.com/user-attachments/assets/ae8a860c-cfa5-4d3a-9374-69e653271a00)

[Judo_blue_brown_belt.pdf](https://github.com/user-attachments/files/17610921/Judo_blue_brown_belt.pdf)
[Judo_brown_black_belt.pdf](https://github.com/user-attachments/files/17610922/Judo_brown_black_belt.pdf)
[Judo_green_blue_belt.pdf](https://github.com/user-attachments/files/17610923/Judo_green_blue_belt.pdf)
[Judo_orange_green_belt.pdf](https://github.com/user-attachments/files/17610924/Judo_orange_green_belt.pdf)
[Judo_purple_brown_belt.pdf](https://github.com/user-attachments/files/17610925/Judo_purple_brown_belt.pdf)
[Judo_yellow_orange_belt.pdf](https://github.com/user-attachments/files/17610926/Judo_yellow_orange_belt.pdf)
[Judo_yellow_white_belt.pdf](https://github.com/user-attachments/files/17610927/Judo_yellow_white_belt.pdf)

**Comment by cpierquet** [comment]
Tks :-)
I can try with your belts, and include them in the packages, with a mention of your contribution ^_^

**Comment by fregattenfahrer** [comment]
Good morning Cedric,

Just reviewed your files and checked the colors. They do not match - I'll be updating the colors so they do match your first release. Just give me a little time - maybe sometime after lunch it'll be ready.

**Comment by cpierquet** [comment]
No problem, tell me the correct colors ;-)
I modify a little the svg (to correct a small path), but with correct colors I can do the modifications ;-)

Céd-

**Comment by fregattenfahrer** [comment]
Hey Cedric,

things went faster as I could expect :). Had a little time in between and just adopted colors and namings (in fact - for yellow white the colors need to be inverted, as you promote from WHITE to YELLOW...). Find attached SVG and PDF files - matched colors from your PDF contained in the package.

[Judo_blue_brown_belt.pdf](https://github.com/user-attachments/files/17616256/Judo_blue_brown_belt.pdf)
![Judo_blue_brown_belt](https://github.com/user-attachments/assets/773f5d36-0d7f-4322-b385-585ad1b92f2f)
[Judo_blue_purple_belt.pdf](https://github.com/user-attachments/files/17616258/Judo_blue_purple_belt.pdf)
![Judo_blue_purple_belt](https://github.com/user-attachments/assets/531018a7-feb6-45c6-b24d-0758846a2bff)
[Judo_brown_black_belt.pdf](https://github.com/user-attachments/files/17616259/Judo_brown_black_belt.pdf)
![Judo_brown_black_belt](https://github.com/user-attachments/assets/0484e7ae-0f27-4d14-b385-c04841abdcf1)
[Judo_green_blue_belt.pdf](https://github.com/user-attachments/files/17616260/Judo_green_blue_belt.pdf)
![Judo_green_blue_belt](https://github.com/user-attachments/assets/8f5292ff-ff25-4860-8e8f-1b0dcb83b495)
[Judo_orange_green_belt.pdf](https://github.com/user-attachments/files/17616261/Judo_orange_green_belt.pdf)
![Judo_orange_green_belt](https://github.com/user-attachments/assets/b9267892-1634-4d39-91e5-e516a4d37ee3)
[Judo_purple_brown_belt.pdf](https://github.com/user-attachments/files/17616262/Judo_purple_brown_belt.pdf)
![Judo_purple_brown_belt](https://github.com/user-attachments/assets/673d4186-db47-4d1d-baed-11d6ef43abe4)
[Judo_white_yellow_belt.pdf](https://github.com/user-attachments/files/17616263/Judo_white_yellow_belt.pdf)
![Judo_white_yellow_belt](https://github.com/user-attachments/assets/5bcafee2-27c8-4f8b-bdf8-2116c2016417)
[Judo_yellow_orange_belt.pdf](https://github.com/user-attachments/files/17616264/Judo_yellow_orange_belt.pdf)
![Judo_yellow_orange_belt](https://github.com/user-attachments/assets/70902c91-543d-41cf-b8c4-e2be972a4b78)

**Comment by fregattenfahrer** [comment]
Another comment here -> if you need the SVG files, you need to rightclick and "Save Target as..." - as GitHub does inline rendering here - and if you click on the SVG, the file is rendered wrong, as like it opens the wrong attachment... "Save target as..." works fine (or "Save Link as..." or similar :))

**Comment by cpierquet** [comment]
Tks, I get back your file, and insert into package ^^
